# Generated by Django 4.2.1 on 2023-09-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_useraccount',
            old_name='accountType',
            new_name='accounttype',
        ),
    ]
