# Generated by Django 4.2.1 on 2023-09-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_accounttype_tbl_useraccount_accounttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_useraccount',
            old_name='accounttype',
            new_name='accountType',
        ),
    ]
