# Generated by Django 4.2.1 on 2023-09-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_accounttype_tbl_useraccount_accounttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sellerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_sellerDetails',
            },
        ),
        migrations.CreateModel(
            name='tbl_staffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('staffid', models.IntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_staffDetails',
            },
        ),
        migrations.RemoveField(
            model_name='tbl_useraccount',
            name='accountType',
        ),
        migrations.AddField(
            model_name='tbl_userdetails',
            name='accountType',
            field=models.CharField(default=2.3, max_length=30),
            preserve_default=False,
        ),
    ]
