# Generated by Django 4.0.4 on 2023-09-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tbl_sellerdetails_tbl_staffdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_sellerdetails',
            name='accountType',
        ),
        migrations.RemoveField(
            model_name='tbl_staffdetails',
            name='accountType',
        ),
        migrations.RemoveField(
            model_name='tbl_userdetails',
            name='accountType',
        ),
        migrations.AddField(
            model_name='tbl_useraccount',
            name='accountType',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
