# Generated by Django 4.2.1 on 2023-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tbl_sellerdetails_accounttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('brandname', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='tbl_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=30)),
                ('brandname', models.CharField(max_length=30)),
                ('modelname', models.CharField(max_length=30)),
                ('offer', models.CharField(max_length=50)),
                ('start_date', models.DateField(max_length=30)),
                ('end_date', models.DateField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_offer',
            },
        ),
        migrations.CreateModel(
            name='tbl_productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=30)),
                ('brandname', models.CharField(max_length=30)),
                ('modelname', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('offer', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=30)),
                ('playback', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_productDetails',
            },
        ),
    ]
