# Generated by Django 4.2.1 on 2023-09-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tbl_feedback_tbl_offer_tbl_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_productdetails',
            name='photo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
