# Generated by Django 4.2.1 on 2023-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tbl_productdetails_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=30)),
                ('brandname', models.CharField(max_length=30)),
                ('sellername', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=30)),
                ('brandname', models.CharField(max_length=30)),
                ('sellername', models.CharField(max_length=30)),
                ('order_date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
                ('total_amount', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.AlterField(
            model_name='tbl_offer',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_offer',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_productdetails',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
