# Generated by Django 4.2.1 on 2023-09-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tbl_cart_tbl_order_alter_tbl_offer_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='total_amount',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
