# Generated by Django 4.2.1 on 2023-09-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tbl_cart_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cart',
            old_name='productname',
            new_name='modelname',
        ),
    ]
