# Generated by Django 4.2.1 on 2023-09-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_productname_tbl_cart_modelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_order',
            old_name='productname',
            new_name='modelname',
        ),
    ]
