# Generated by Django 4.2.1 on 2023-10-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_productname_tbl_order_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='photo',
            field=models.CharField(default=9.09, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_order',
            name='photo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_productdetails',
            name='photo',
            field=models.CharField(max_length=50),
        ),
    ]
