# Generated by Django 4.2.1 on 2023-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tbl_cart_photo_tbl_order_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tbl_order',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
