# Generated by Django 4.2.1 on 2023-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_tbl_cart_photo_alter_tbl_order_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='photo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_order',
            name='photo',
            field=models.CharField(max_length=50),
        ),
    ]
