# Generated by Django 4.0.4 on 2023-10-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_tbl_cart_photo_alter_tbl_order_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='brandname',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='modelname',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='photo',
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='product_id',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
