# Generated by Django 4.0.4 on 2023-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_tbl_cart_brandname_remove_tbl_cart_modelname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
    ]
