# Generated by Django 4.0.4 on 2023-10-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_tbl_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='price',
        ),
    ]
