# Generated by Django 4.0.4 on 2023-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_tbl_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cart',
            old_name='product_id',
            new_name='brandname',
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='modelname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='photo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
